### ISSUE TITLE
Caching support

### ISSUE THREAD

**Issue by user529481** [tylerjrichards/st-filter-dataframe#4]
Hi Tyler, thanks for putting together this project. I've tried it out and it's super easy to use. I was wondering if you'd consider adding some kind of session support. I was hoping to include this in my project but simply enabling the filter triggers a refresh of my entire page triggering some pipelines to rerun which can take a while. 

It would be interesting to embed the filter in some kind of streamlit form

**Comment by tylerjrichards** [comment]
hey! by definition, streamlit won't run anything while inside a form until you click the submit button, so that wouldn't really work as a solution. 

Have you thought about caching the non-streamlit filter part of your app? That sounds like it is the actual problem here, which really isn't something that this function can help with

**Comment by user529481** [comment]
That's an interesting avenue. I'll give that a try, thanks!
